# Generated by Django 3.1.5 on 2021-01-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='target',
            new_name='target_user',
        ),
    ]
